pipeline {
  agent any

  tools {
    nodejs 'node25'
  }

  stages {
    stage('Install Dependencies') {
      steps {
        sh 'node -v'
        sh 'npm -v'
        sh 'npm install'
      }
    }

    stage('Build Frontend') {
      steps {
        sh 'npm run build'
      }
    }
  }
}
